builds:
  - main: dummy.go
    goos:
      - linux
    #      - windows
    #      - darwin
    goarch:
      - amd64
    binary: app
    hooks:
      post: |
        set -uex
        readonly DIST_DIR="dist"
        readonly BINARY_NAME="app"
        function build() { v -o "dist/$(ls -d "${DIST_DIR}"/*${1}* |head -n 1)" -os "${1}" -message-limit 0 main.v }
        build "linux"
        #  build "windows"
        #  build "darwin"
# archives.replacements - Deprecation notices - GoReleaser https://goreleaser.com/deprecations/?h=replacements#archivesreplacements
archives:
  - id: main
    name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    replacements:
      linux: Linux
      windows: Windows
      darwin: macOS
      #     いらないので無効化
      #     386: i386
      amd64: x86_64
# プロジェクトの完全なビルドを生成したいが、何も検証したくないし、どこかにアップロードもしたくないという場合があります。
# GoReleaser は --snapshot フラグとスナップショット カスタマイズ セクションでこれをサポートします。
# snapshots - Snapshots - GoReleaser https://goreleaser.com/customization/snapshots/?h=snapshot#snapshots
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
